package initcmd

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"text/template"
	"time"
)

// CRAInitConfig holds the configuration for CRA initialization.
type CRAInitConfig struct {
	ProductName     string
	Manufacturer    string
	Category        string // default, important-class-1, important-class-2, critical
	SecurityContact string
	SupportEndDate  string
	CSIRTContact    string
}

// DefaultCRAConfig returns a CRA config with sensible defaults.
func DefaultCRAConfig() CRAInitConfig {
	return CRAInitConfig{
		Category:       "default",
		SupportEndDate: time.Now().AddDate(5, 0, 0).Format("2006-01-02"),
	}
}

// ValidCategories returns the list of valid CRA product categories.
func ValidCategories() []string {
	return []string{"default", "important-class-1", "important-class-2", "critical"}
}

// ValidateCategory checks if the category is valid.
func ValidateCategory(cat string) bool {
	for _, v := range ValidCategories() {
		if v == cat {
			return true
		}
	}
	return false
}

const craYAMLTemplate = `# Chainsaw CRA Compliance Configuration
# Generated by: chainsaw init-cra
# Date: {{.Date}}

policy:
  fail-on: high
  ignore: []
  licences:
    mode: deny
    deny-list:
      - GPL-3.0-only
      - AGPL-3.0-only

cra:
  required-score: 70
  manufacturer: "{{.Manufacturer}}"
  security-contact: "{{.SecurityContact}}"
  support-end-date: "{{.SupportEndDate}}"
  csirt-contact: "{{.CSIRTContact}}"

supply-chain:
  min-pinning-score: 80
  require-sha-pins: false

licences:
  mode: deny
  deny-list:
    - GPL-3.0-only
    - AGPL-3.0-only
  allow-list:
    - MIT
    - Apache-2.0
    - BSD-2-Clause
    - BSD-3-Clause
    - ISC
    - MPL-2.0
`

// WriteCRAConfig generates a .chainsaw.yaml configured for CRA compliance.
func WriteCRAConfig(dir string, cfg CRAInitConfig) (string, error) {
	tmpl, err := template.New("cra").Parse(craYAMLTemplate)
	if err != nil {
		return "", fmt.Errorf("parsing template: %w", err)
	}

	path := filepath.Join(dir, ".chainsaw.yaml")

	// Don't overwrite existing file.
	if _, err := os.Stat(path); err == nil {
		return "", fmt.Errorf(".chainsaw.yaml already exists; use --force to overwrite")
	}

	f, err := os.Create(path)
	if err != nil {
		return "", fmt.Errorf("creating config file: %w", err)
	}
	defer f.Close()

	data := struct {
		Date            string
		Manufacturer    string
		SecurityContact string
		SupportEndDate  string
		CSIRTContact    string
	}{
		Date:            time.Now().Format("2006-01-02"),
		Manufacturer:    cfg.Manufacturer,
		SecurityContact: cfg.SecurityContact,
		SupportEndDate:  cfg.SupportEndDate,
		CSIRTContact:    cfg.CSIRTContact,
	}

	if err := tmpl.Execute(f, data); err != nil {
		return "", fmt.Errorf("executing template: %w", err)
	}

	return path, nil
}

// WriteCRAConfigForce generates .chainsaw.yaml, overwriting if it exists.
func WriteCRAConfigForce(dir string, cfg CRAInitConfig) (string, error) {
	path := filepath.Join(dir, ".chainsaw.yaml")

	tmpl, err := template.New("cra").Parse(craYAMLTemplate)
	if err != nil {
		return "", fmt.Errorf("parsing template: %w", err)
	}

	f, err := os.Create(path)
	if err != nil {
		return "", fmt.Errorf("creating config file: %w", err)
	}
	defer f.Close()

	data := struct {
		Date            string
		Manufacturer    string
		SecurityContact string
		SupportEndDate  string
		CSIRTContact    string
	}{
		Date:            time.Now().Format("2006-01-02"),
		Manufacturer:    cfg.Manufacturer,
		SecurityContact: cfg.SecurityContact,
		SupportEndDate:  cfg.SupportEndDate,
		CSIRTContact:    cfg.CSIRTContact,
	}

	if err := tmpl.Execute(f, data); err != nil {
		return "", fmt.Errorf("executing template: %w", err)
	}

	return path, nil
}

// FormatNextSteps returns guidance after init-cra runs.
func FormatNextSteps(category string) string {
	var sb strings.Builder
	sb.WriteString("\nNext steps:\n")
	sb.WriteString("  1. Review and customize .chainsaw.yaml\n")
	sb.WriteString("  2. Run 'chainsaw comply' to see your baseline CRA score\n")
	sb.WriteString("  3. Run 'chainsaw check' to see all findings\n")

	switch category {
	case "important-class-1", "important-class-2":
		sb.WriteString("  4. Prepare conformity self-assessment (EU-type examination for Class II)\n")
		sb.WriteString("  5. Monitor Notified Body availability (deadline: 2026-06-11)\n")
	case "critical":
		sb.WriteString("  4. Engage a Notified Body for third-party conformity assessment\n")
		sb.WriteString("  5. Monitor Notified Body designation (deadline: 2026-06-11)\n")
	default:
		sb.WriteString("  4. Prepare manufacturer self-assessment documentation\n")
	}

	sb.WriteString("  5. Set up vulnerability reporting workflow (deadline: 2026-09-11)\n")
	return sb.String()
}
