package initcmd

import (
	"fmt"
	"os"
	"path/filepath"
)

const gitlabCITemplate = `# Chainsaw Security Pipeline for GitLab CI
# Generated by: chainsaw init-ci --platform gitlab

stages:
  - build
  - scan
  - comply

variables:
  CHAINSAW_VERSION: "latest"
  GO_VERSION: "1.26"

build:
  stage: build
  image: golang:${GO_VERSION}
  script:
    - go build -o chainsaw ./cmd/chainsaw/
  artifacts:
    paths:
      - chainsaw
    expire_in: 1 hour

scan:
  stage: scan
  dependencies:
    - build
  script:
    - ./chainsaw scan --format sarif --output scan-result.sarif .
    - ./chainsaw scan --format json --output scan-result.json .
  artifacts:
    paths:
      - scan-result.sarif
      - scan-result.json
    reports:
      sast:
        - scan-result.sarif
    expire_in: 30 days
  allow_failure: false

comply:
  stage: comply
  dependencies:
    - build
  script:
    - ./chainsaw check --quiet .
    - ./chainsaw comply --format json --output comply-result.json .
  artifacts:
    paths:
      - comply-result.json
    expire_in: 30 days
  allow_failure: false

sbom:
  stage: comply
  dependencies:
    - build
  script:
    - ./chainsaw sbom --format json --output sbom.cdx.json .
  artifacts:
    paths:
      - sbom.cdx.json
    expire_in: 30 days
`

// WriteGitLabCI generates a .gitlab-ci.yml file.
func WriteGitLabCI(dir string) (string, error) {
	path := filepath.Join(dir, ".gitlab-ci.yml")

	if _, err := os.Stat(path); err == nil {
		return "", fmt.Errorf(".gitlab-ci.yml already exists; remove it first or use a different directory")
	}

	if err := os.WriteFile(path, []byte(gitlabCITemplate), 0644); err != nil {
		return "", fmt.Errorf("writing gitlab CI file: %w", err)
	}

	return path, nil
}
