package initcmd

import (
	"fmt"
	"os"
	"path/filepath"
)

const nativeHookTemplate = `#!/bin/sh
# Chainsaw pre-commit hook
# Generated by: chainsaw init-hooks
# Runs chainsaw scan on lockfile changes to catch vulnerabilities before commit.

# Check if any lockfiles are staged for commit.
LOCKFILES="go.sum package-lock.json pnpm-lock.yaml yarn.lock Cargo.lock mix.lock requirements.txt Pipfile.lock composer.lock"
CHANGED=0
for f in $LOCKFILES; do
  if git diff --cached --name-only | grep -q "$f"; then
    CHANGED=1
    break
  fi
done

if [ "$CHANGED" -eq 0 ]; then
  exit 0
fi

echo "Chainsaw: lockfile changed, running security scan..."
chainsaw scan --quiet --format table .
RESULT=$?

if [ "$RESULT" -ne 0 ]; then
  echo "Chainsaw: security findings detected. Review before committing."
  echo "To bypass: git commit --no-verify (not recommended)"
  exit 1
fi

echo "Chainsaw: scan passed."
exit 0
`

const preCommitFrameworkTemplate = `# Chainsaw pre-commit framework configuration
# Generated by: chainsaw init-hooks --framework pre-commit
# See https://pre-commit.com for more info.
repos:
  - repo: local
    hooks:
      - id: chainsaw-scan
        name: Chainsaw Security Scan
        entry: chainsaw scan --quiet .
        language: system
        files: "(go\\.sum|package-lock\\.json|pnpm-lock\\.yaml|yarn\\.lock|Cargo\\.lock|mix\\.lock|requirements\\.txt|Pipfile\\.lock|composer\\.lock)$"
        pass_filenames: false
        stages: [pre-commit]
`

// WriteNativeHook writes a native git pre-commit hook.
func WriteNativeHook(dir string) (string, error) {
	hooksDir := filepath.Join(dir, ".git", "hooks")
	if _, err := os.Stat(hooksDir); os.IsNotExist(err) {
		return "", fmt.Errorf(".git/hooks directory not found; is this a git repository?")
	}

	path := filepath.Join(hooksDir, "pre-commit")
	if _, err := os.Stat(path); err == nil {
		return "", fmt.Errorf("pre-commit hook already exists; remove it first or use --force")
	}

	if err := os.WriteFile(path, []byte(nativeHookTemplate), 0755); err != nil {
		return "", fmt.Errorf("writing pre-commit hook: %w", err)
	}

	return path, nil
}

// WritePreCommitConfig writes a .pre-commit-config.yaml file.
func WritePreCommitConfig(dir string) (string, error) {
	path := filepath.Join(dir, ".pre-commit-config.yaml")
	if _, err := os.Stat(path); err == nil {
		return "", fmt.Errorf(".pre-commit-config.yaml already exists; remove it first or use --force")
	}

	if err := os.WriteFile(path, []byte(preCommitFrameworkTemplate), 0644); err != nil {
		return "", fmt.Errorf("writing pre-commit config: %w", err)
	}

	return path, nil
}

// WriteNativeHookForce writes a native git pre-commit hook, overwriting if exists.
func WriteNativeHookForce(dir string) (string, error) {
	hooksDir := filepath.Join(dir, ".git", "hooks")
	if _, err := os.Stat(hooksDir); os.IsNotExist(err) {
		return "", fmt.Errorf(".git/hooks directory not found; is this a git repository?")
	}

	path := filepath.Join(hooksDir, "pre-commit")
	if err := os.WriteFile(path, []byte(nativeHookTemplate), 0755); err != nil {
		return "", fmt.Errorf("writing pre-commit hook: %w", err)
	}

	return path, nil
}
